"""Human-readable source audit, rendered from the inventory and join report only."""

from __future__ import annotations

from typing import Any


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_audit(inventory: dict[str, Any], join: dict[str, Any], rows: dict[str, int]) -> str:
    lines = [
        f"# Project-data source audit — {inventory['dataset_name']}",
        "",
        "Generated by `regkg ingest`. Values are recomputed from the supplied files, not copied from the plan.",
        "",
        "## Sources",
        "",
        "| Role | Path | SHA-256 | Bytes | Data rows | Columns | Zeros | Min | Max |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for source in inventory["sources"]:
        lines.append(
            "| "
            + " | ".join(
                _cell(v)
                for v in (
                    source["role"],
                    source["path"],
                    f"`{source['sha256'][:16]}…`",
                    source["bytes"],
                    source["n_data_rows"],
                    source["n_columns"],
                    source["zero_value_count"],
                    source["numeric_min"],
                    source["numeric_max"],
                )
            )
            + " |"
        )
    contexts, genes, scope = join["contexts"], join["genes"], join["scope_chromlinker"]
    lines += [
        "",
        "Duplicate semantic keys and non-finite measurements abort ingestion, so every listed source has none.",
        "",
        "## Output rows",
        "",
        *[f"- `{name}`: {count:,}" for name, count in sorted(rows.items())],
        "",
        "## Contexts and niches",
        "",
        f"- Expression context labels: {contexts['expression_labels']}; ChromLinker: {contexts['chromlinker_labels']}; "
        f"ChromLinker labels absent from expression: {len(contexts['chromlinker_labels_absent_from_expression'])}.",
        f"- Niche-specific labels: expression {contexts['niche_specific_labels']['expression']}, "
        f"ChromLinker {contexts['niche_specific_labels']['chromlinker']}.",
        f"- Niche contexts without ChromLinker columns (not manufactured): "
        f"{', '.join(contexts['niche_labels_absent_from_chromlinker']) or 'none'}.",
        f"- Niche states: {contexts['niche_states']} (condition-pooled) "
        f"from {contexts['definition_runs']} definition runs; "
        f"biological contexts: {contexts['biological_contexts']}; cell types: {contexts['cell_types']}.",
        f"- {scope['cell_type']} ChromLinker values: {scope['values']:,} across {len(scope['contexts'])} contexts, "
        f"{scope['nonzero_values']:,} nonzero ({scope['note']}).",
        "",
        "## Niche-expression signature groups",
        "",
        "Descriptive Niche2-minus-Niche1 pooled mean log-normalized expression; not formal DE. "
        "Donor counts not supplied.",
        "",
        "| Cell type | Condition | Genes | Niche 1 cells | Niche 2 cells "
        "| Expression niche columns | ChromLinker niche columns |",
        "|---|---|---:|---:|---:|---|---|",
    ]
    for group in join["signature_groups"]:
        lines.append(
            f"| {_cell(group['cell_type'])} | {_cell(group['condition'])} | {group['n_genes']:,} | "
            f"{group['n_cells_niche1']:,} | {group['n_cells_niche2']:,} | "
            f"{'yes' if group['expression_has_both_niche_contexts'] else 'no'} | "
            f"{'yes' if group['chromlinker_has_both_niche_contexts'] else 'no'} |"
        )
    lines += [
        "",
        "## Neighborhood profiles",
        "",
        "| Focal type | k | Resolution | Reported categories | Unreported (not zero-filled) | Row sums |",
        "|---|---:|---:|---:|---|---|",
    ]
    for item in join["neighborhoods"]:
        lines.append(
            f"| {_cell(item['focal_cell_type'])} | {item['k_neighbors']} | {item['clustering_resolution']} | "
            f"{item['reported_categories']} | {_cell(', '.join(item['unreported_categories']) or 'none')} | "
            f"{', '.join(f'{s:.12g}' for s in item['row_sums'])} |"
        )
    lines += [
        "",
        "## Genes",
        "",
        f"- Source symbols: {genes['total_source_symbols']:,} (ChromLinker TFs {genes['chromlinker_tfs']}, "
        f"targets {genes['chromlinker_targets']:,}, expression {genes['expression']:,}, "
        f"signatures {genes['niche_signatures']:,}). All retain `unresolved_external_id`.",
        "",
        "| Unmatched set | Count | Examples |",
        "|---|---:|---|",
        *[
            f"| {name} | {item['count']:,} | {_cell(', '.join(item['examples'][:10]))} |"
            for name, item in genes["unmatched"].items()
        ],
        "",
        f"Suffix-variant diagnostic ({genes['suffix_variant_diagnostic']['note']}): "
        f"{genes['suffix_variant_diagnostic']['count']} symbols.",
        "",
        "## Scope TF seeds",
        "",
        *[
            f"- {seed}: ChromLinker TF {flags['in_chromlinker_tf']}, expression {flags['in_expression']}, "
            f"signatures {flags['in_niche_signatures']}"
            for seed, flags in join["scope_tf_seeds"].items()
        ],
        "",
    ]
    return "\n".join(lines)
